using Azure.Storage.Blobs;
using Azure.Storage.Sas;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SpendSmart.Report.API.Repositories;

namespace SpendSmart.Report.API.Services;

public class ReportService : IReportService
{
    private readonly IReportRepository _repo;
    private readonly IConfiguration _config;
    private readonly BlobContainerClient _containerClient;

    public ReportService(IReportRepository repo, IConfiguration config)
    {
        _repo = repo;
        _config = config;

        var connStr = _config["AzureBlob:ConnectionString"] 
                      ?? throw new Exception("Azure Blob connection string is not configured.");
        _containerClient = new BlobContainerClient(connStr, "reports");
    }

    public async Task<Models.Report> GenerateReportAsync(int userId, string type, string title, string? parameters)
    {
        var report = new Models.Report
        {
            UserId = userId,
            ReportType = type,
            Title = title,
            Parameters = parameters,
            Status = "GENERATING"
        };
        
        await _repo.AddAsync(report);

        try
        {
            // 1. Generate PDF using QuestPDF
            var pdfStream = new MemoryStream();
            
            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(12));
                    
                    page.Header()
                        .Text($"SpendSmart {type} Report")
                        .SemiBold().FontSize(24).FontColor(Colors.Blue.Darken2);
                    
                    page.Content()
                        .PaddingVertical(1, Unit.Centimetre)
                        .Column(x =>
                        {
                            x.Spacing(20);
                            x.Item().Text($"Title: {title}").FontSize(16);
                            x.Item().Text($"Date Generated: {DateTime.UtcNow.ToString("g")}");
                            x.Item().Text($"Parameters: {parameters ?? "None"}");
                            x.Item().Text("This report was automatically generated by SpendSmart Report Service.");
                        });
                        
                    page.Footer()
                        .AlignCenter()
                        .Text(x =>
                        {
                            x.Span("Page ");
                            x.CurrentPageNumber();
                        });
                });
            }).GeneratePdf(pdfStream);

            pdfStream.Position = 0;

            // 2. Upload to Azure Blob Storage
            await _containerClient.CreateIfNotExistsAsync();
            var blobName = $"{userId}/{report.ReportId}_{Guid.NewGuid()}.pdf";
            var blobClient = _containerClient.GetBlobClient(blobName);
            
            await blobClient.UploadAsync(pdfStream, overwrite: true);

            // 3. Update database
            report.FilePath = blobName;
            report.Status = "COMPLETED";
            await _repo.UpdateAsync(report);
        }
        catch (Exception ex)
        {
            report.Status = "FAILED";
            await _repo.UpdateAsync(report);
            // Log exception here...
            throw;
        }

        return report;
    }

    public async Task<string> GetReportSasUrlAsync(int reportId)
    {
        var report = await _repo.GetByIdAsync(reportId);
        if (report == null || string.IsNullOrEmpty(report.FilePath) || report.Status != "COMPLETED")
            throw new Exception("Report not found or not ready.");

        var blobClient = _containerClient.GetBlobClient(report.FilePath);
        
        var sasUri = blobClient.GenerateSasUri(BlobSasPermissions.Read,
            DateTimeOffset.UtcNow.AddHours(24));
            
        return sasUri.ToString();
    }

    public async Task DeleteReportAsync(int reportId, int userId)
    {
        var report = await _repo.GetByIdAsync(reportId);
        if (report == null || report.UserId != userId)
            throw new UnauthorizedAccessException("Report not found or access denied.");

        if (!string.IsNullOrEmpty(report.FilePath))
        {
            var blobClient = _containerClient.GetBlobClient(report.FilePath);
            await blobClient.DeleteIfExistsAsync();
        }

        await _repo.DeleteAsync(report);
    }

    public async Task ClearDownloadHistoryAsync(int userId)
    {
        var reports = await _repo.GetAllForUserAsync(userId);
        foreach (var report in reports)
        {
            if (!string.IsNullOrEmpty(report.FilePath))
            {
                var blobClient = _containerClient.GetBlobClient(report.FilePath);
                await blobClient.DeleteIfExistsAsync();
            }
        }
        await _repo.DeleteAllForUserAsync(userId);
    }
}
